plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:
  'styled-components@*':
    dependencies:
      'react-is': '^18.2.0'
